spring:
# datasource:
#  driver-class-name: org.postgresql.Driver
#  url: jdbc:postgresql://dev-egis-rds-instance-1.cvkjvlq4r4bh.ap-northeast-2.rds.amazonaws.com:5432/egis
#  username: postgres
#  password: egis2022!
 thymeleaf:
  cache: false
  check-template-location: true
  prefix: classpath:/templates/
  suffix: .html
 mvc:
  throw-exception-if-no-handler-found: true
  static-path-pattern: /static/**
 web:
   resources:
    static-locations: classpath:/static/
    add-mappings: true
    
#logging:
 #config: classpath:logging-config.xml
 
file:
 xddata:
  path: E:\vwdata\dp\test\
  new-path: E:\vwdata\dp\test\
#  linux-path: /usr/local/egis/data/build/seoul/gangnamgu/